project:
  type: website
  resources:
    - "Newsletter/*.png"
    - "Newsletter/*.jpg"
    - "Newsletter/*.html"
    - "Newsletter/*.jpeg"

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: OSIG Newsletter
        menu:
          - text: "Newsletter 11th Issue: June 2025"
            href: Newsletter/NL_June.html
          - text: "Newsletter 12th Issue: October 2025"
            href: Newsletter/NL_October.html
          - text: "Newsletter 13th Issue: February 2026"
            href: Newsletter/NL_February_2026.html
          - text: "Previous Newsletters"
            href: https://uol.de/psychologie/open-science/osig
      - href: oosc.qmd
        text: 1st OOSC
  page-footer:
    left: |
      Â© 2025 Open Science Interest Group (OSIG)
    right: |
      [Imprint](https://uol.de/impressum) | [Privacy](https://uol.de/dism)


format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
